### ISSUE TITLE
Possible helpful resource

### ISSUE THREAD

**Issue by perigoso** [catppuccin/kde#36]
From what I saw this was one of the more troublesome ports, with licensing issues in the mix, though I see that has been dealt with..
Either way, I thought I should drop this project here, in case the maintainers are not aware of it, it can be a helpful resource, it's a couple of KDE theming bits using the Catppuccin palette, by jomada (author of some great themes like Moe/MoeDark), licensed with MIT

https://gitlab.com/jomada/Scratchy
https://gitlab.com/jomada/Itchy

**Comment by Sourcastic** [comment]
Yup, we are aware of those themes as well. The problem is the bit that's GPL in our theme is the QtWidgets theme, aka the Plasma Theme. Itchy and Scratchy don't have custom plasma themes and just use default breeze. We wanted to package a plasma theme, but doing so caused some problems that led us to modify it.

And of course, for everything else they have, we already do have.

**Comment by perigoso** [comment]
Fair, I am not aware of the intricacies of the problem, just wanted to make sure it was known, feel free to close

**Comment by perigoso** [comment]
Fair, I am not aware of the intricacies of the problem, just wanted to make sure it was known
