### ISSUE TITLE
Window Decoration Scaling Broken On Wayland

### ISSUE THREAD

**Issue by iamthetoaster** [catppuccin/kde#41]
After a minute, when windows are scaled, their decorations are scaled incorrectly. 

![catppuccin_decorations_broken](https://user-images.githubusercontent.com/14080501/231539266-9621ecb1-8085-4bc3-acf1-5545873a759e.png)

This does not appear to happen on xorg.

**Comment by justTOBBI** [comment]
What version of KDE are you on?
This doesnt happen for me on KDE 5.27 with wayland

**Comment by Sourcastic** [comment]
I have seen this before, though not in a while. It seems to be a KDE bug introduced in KWin 5.27 that's been reported multiple times by different people. It does seem to be marked as fixed in 5.27.4. So do try updating and see if that helps. Regardless, I don't think this is a bug that's a fault of the window decorations theme.

A link to the bug report: https://bugs.kde.org/show_bug.cgi?id=465790

**Comment by iamthetoaster** [comment]
I'm on KDE version 5.27.1. 
Thanks, I'll try updating!

**Comment by Sourcastic** [comment]
Also, one tiny workaround if it does not fix itself:
In system settings, you can assign a shortcut like Meta + B  to "Toggle Window Titlebar." That'll make a window's titlebar disappear and reappear. You can reset the window decorations quickly that way.

**Comment by iamthetoaster** [comment]
Updating to 5.27.4 worked, thanks y'all!
