### ISSUE TITLE
(Bug?) Can't resize window from top edge

### ISSUE THREAD

**Issue by jwols27** [catppuccin/kde#84]
Resizing windows from the top edge doesn't work, bottom edge works fine though. Tried with Breeze and had no problems, so I'm assuming the bug comes from the Catppuccin Window Decoration.

- KDE Plasma 6.2.4
- Catppuccin KDE Frappe Modern (Mauve)
- KWin Wayland

**Comment by Sourcastic** [comment]
Hi, unfortunately, this seems like a KDE bug with the “no-borders” setting rather than a bug with Catppuccin. It's a bug with any custom window decorations you download from the store. Here's the bug report: https://bugs.kde.org/show_bug.cgi?id=417716. There's nothing we can really do.

Pro-tip btw: Instead of finagling with the edges of a window, super + right click can also resize a window when a cursor is just *near* any edge. Also, you can try changing the border size and that should fix it as well.

**Comment by jwols27** [comment]
Oh, I see. Also, that tip is actually super helpful, I didn't know. Thanks!
